# Generated by Django 4.1.5 on 2023-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
